import { type User, type Initiative, type Task, type InitiativeRating, type UserRating, type DailyCheckin, type Attachment } from './types';

const users: User[] = [
    { id: '1', name: 'Alia Hassan', email: 'alia.hassan@example.com', role: 'Admin', businessUnit: 'Executive', designation: 'CEO', avatarUrl: 'https://picsum.photos/seed/1/40/40' },
    { id: '2', name: 'Ben Carter', email: 'ben.carter@example.com', role: 'Initiative Lead', businessUnit: 'Technology', designation: 'VP of Engineering', avatarUrl: 'https://picsum.photos/seed/2/40/40' },
    { id: '3', name: 'Chloe Davis', email: 'chloe.davis@example.com', role: 'Team Member', businessUnit: 'Marketing', designation: 'Marketing Manager', avatarUrl: 'https://picsum.photos/seed/3/40/40' },
    { id: '4', name: 'David Evans', email: 'david.evans@example.com', role: 'Viewer', businessUnit: 'Finance', designation: 'CFO', avatarUrl: 'https://picsum.photos/seed/4/40/40' },
    { id: '5', name: 'Eva Green', email: 'eva.green@example.com', role: 'Initiative Lead', businessUnit: 'Legal', designation: 'General Counsel', avatarUrl: 'https://picsum.photos/seed/5/40/40' },
    { id: '6', name: 'Frank Harris', email: 'frank.harris@example.com', role: 'Team Member', businessUnit: 'Operations', designation: 'Operations Lead', avatarUrl: 'https://picsum.photos/seed/6/40/40' },
    { id: '7', name: 'Grace Johnson', email: 'grace.johnson@example.com', role: 'Team Member', businessUnit: 'HR', designation: 'HR Business Partner', avatarUrl: 'https://picsum.photos/seed/7/40/40' },
    { id: '8', name: 'Henry King', email: 'henry.king@example.com', role: 'Initiative Lead', businessUnit: 'Business Excellence', designation: 'Director of Transformation', avatarUrl: 'https://picsum.photos/seed/8/40/40' },
    { id: '9', name: 'Ivy Lee', email: 'ivy.lee@example.com', role: 'Team Member', businessUnit: 'MSW & WTE', designation: 'Project Manager', avatarUrl: 'https://picsum.photos/seed/9/40/40' },
    { id: '10', name: 'Jack Miller', email: 'jack.miller@example.com', role: 'Team Member', businessUnit: 'Technology', designation: 'Software Engineer', avatarUrl: 'https://picsum.photos/seed/10/40/40' },
    { id: '11', name: 'Kara Nelson', email: 'kara.nelson@example.com', role: 'Team Member', businessUnit: 'Finance', designation: 'Financial Analyst', avatarUrl: 'https://picsum.photos/seed/11/40/40' },
    { id: '12', name: 'Leo Olsen', email: 'leo.olsen@example.com', role: 'Team Member', businessUnit: 'Legal', designation: 'Paralegal', avatarUrl: 'https://picsum.photos/seed/12/40/40' },
    { id: '13', name: 'Mia Perez', email: 'mia.perez@example.com', role: 'Initiative Lead', businessUnit: 'HR', designation: 'VP of HR', avatarUrl: 'https://picsum.photos/seed/13/40/40' },
];

const initiatives: Initiative[] = [
  { id: '1', name: 'Review all agreements', theme: 'Legal', description: 'Comprehensive review of all existing legal agreements.', objectives: 'Identify risks and opportunities in current contracts.', leads: ['5'], teamMembers: ['12'], status: 'In Progress', priority: 'High', startDate: '2024-01-15', targetEndDate: '2024-06-30', tags: ['Legal', 'Contracts'], ragStatus: 'Green', progress: 60 },
  { id: '2', name: 'Restructure legal department', theme: 'Legal', description: 'Reorganize the legal team for better efficiency.', objectives: 'Align legal team structure with business priorities.', leads: ['5'], teamMembers: ['12', '7'], status: 'In Progress', priority: 'Medium', startDate: '2024-02-01', targetEndDate: '2024-08-31', tags: ['Legal', 'HR'], ragStatus: 'Amber', progress: 45 },
  { id: '3', name: 'Improve litigation process', theme: 'Legal', description: 'Streamline the process for handling litigations.', objectives: 'Reduce litigation time and costs.', leads: ['5'], teamMembers: ['12'], status: 'Not Started', priority: 'Medium', startDate: '2024-07-01', targetEndDate: '2024-12-31', tags: ['Legal', 'Process'], ragStatus: 'Green', progress: 0 },
  { id: '4', name: 'New client contract template', theme: 'Legal', description: 'Develop a new standardized client contract template.', objectives: 'Simplify contract negotiation and execution.', leads: ['5'], teamMembers: ['12', '3'], status: 'Completed', priority: 'High', startDate: '2023-10-01', targetEndDate: '2024-01-31', tags: ['Legal', 'Templates'], ragStatus: 'Green', progress: 100 },
  { id: '5', name: 'Internal audit and process review', theme: 'Business Excellence & Transformation', description: 'Conduct a full internal audit of key business processes.', objectives: 'Identify and eliminate process bottlenecks.', leads: ['8'], teamMembers: ['6', '11'], status: 'In Progress', priority: 'High', startDate: '2024-03-01', targetEndDate: '2024-09-30', tags: ['Audit', 'Process'], ragStatus: 'Green', progress: 50 },
  { id: '6', name: 'Digital transformation roadmap', theme: 'Business Excellence & Transformation', description: 'Define the roadmap for the company\'s digital transformation.', objectives: 'Leverage technology to improve business outcomes.', leads: ['2', '8'], teamMembers: ['10', '3'], status: 'In Progress', priority: 'High', startDate: '2024-01-10', targetEndDate: '2024-12-20', tags: ['Digital', 'Strategy'], ragStatus: 'Amber', progress: 30 },
  { id: '7', name: 'Customer experience overhaul', theme: 'Business Excellence & Transformation', description: 'Redesign the end-to-end customer journey and experience.', objectives: 'Increase customer satisfaction and retention.', leads: ['3', '8'], teamMembers: ['6'], status: 'On Hold', priority: 'Medium', startDate: '2024-04-01', targetEndDate: '2024-11-30', tags: ['CX', 'Customer'], ragStatus: 'Red', progress: 20 },
  { id: '8', name: 'Develop MSW masterplan', theme: 'MSW & WTE', description: 'Create a masterplan for Municipal Solid Waste management.', objectives: 'Outline a 10-year strategy for MSW.', leads: ['9'], teamMembers: ['6'], status: 'In Progress', priority: 'High', startDate: '2024-02-15', targetEndDate: '2024-10-31', tags: ['MSW', 'Strategy'], ragStatus: 'Green', progress: 40 },
  { id: '9', name: 'Implement WTE plant technology', theme: 'MSW & WTE', description: 'Implement new technology at the Waste-to-Energy plant.', objectives: 'Increase energy output by 20%.', leads: ['9', '2'], teamMembers: ['10', '6'], status: 'In Progress', priority: 'High', startDate: '2024-03-20', targetEndDate: '2025-01-31', tags: ['WTE', 'Technology'], ragStatus: 'Amber', progress: 25 },
  { id: '10', name: 'Recycling program expansion', theme: 'MSW & WTE', description: 'Expand the city-wide recycling program.', objectives: 'Increase recycling rates by 15%.', leads: ['9'], teamMembers: ['3'], status: 'Completed', priority: 'Medium', startDate: '2023-09-01', targetEndDate: '2024-03-31', tags: ['MSW', 'Recycling'], ragStatus: 'Green', progress: 100 },
  { id: '11', name: 'Employee performance management system', theme: 'HR', description: 'Implement a new system for managing employee performance.', objectives: 'Improve transparency and fairness in performance reviews.', leads: ['13'], teamMembers: ['7', '2'], status: 'In Progress', priority: 'High', startDate: '2024-01-05', targetEndDate: '2024-07-31', tags: ['HR', 'Digital'], ragStatus: 'Green', progress: 70 },
  { id: '12', name: 'Leadership development program', theme: 'HR', description: 'Create a new program for developing future leaders.', objectives: 'Build a strong leadership pipeline.', leads: ['13'], teamMembers: ['7', '8'], status: 'Not Started', priority: 'Medium', startDate: '2024-08-01', targetEndDate: '2025-02-28', tags: ['HR', 'Training'], ragStatus: 'Green', progress: 0 },
  { id: '13', name: 'Revamp employee onboarding', theme: 'HR', description: 'Redesign the onboarding process for new hires.', objectives: 'Improve new hire retention and time-to-productivity.', leads: ['13'], teamMembers: ['7'], status: 'Completed', priority: 'Medium', startDate: '2023-11-01', targetEndDate: '2024-04-30', tags: ['HR', 'Onboarding'], ragStatus: 'Green', progress: 100 },
  { id: '14', name: 'SAP S4 HANA migration', theme: 'Finance', description: 'Migrate the current ERP system to SAP S/4HANA.', objectives: 'Modernize financial systems and reporting.', leads: ['4', '2'], teamMembers: ['11', '10'], status: 'In Progress', priority: 'High', startDate: '2023-06-01', targetEndDate: '2024-12-31', tags: ['Finance', 'Digital'], ragStatus: 'Amber', progress: 65 },
  { id: '15', name: 'Quarterly budgeting process automation', theme: 'Finance', description: 'Automate the quarterly budgeting and forecasting process.', objectives: 'Reduce manual effort and improve forecast accuracy.', leads: ['4'], teamMembers: ['11'], status: 'In Progress', priority: 'Medium', startDate: '2024-05-01', targetEndDate: '2024-10-31', tags: ['Finance', 'Automation'], ragStatus: 'Green', progress: 15 },
  // Adding more to reach 30
  { id: '16', name: 'Data Privacy Compliance (GDPR/CCPA)', theme: 'Legal', description: 'Ensure full compliance with global data privacy regulations.', objectives: 'Audit all data handling processes and update policies.', leads: ['5'], teamMembers: ['12', '2'], status: 'In Progress', priority: 'High', startDate: '2024-03-15', targetEndDate: '2024-09-15', tags: ['Legal', 'Compliance', 'Data'], ragStatus: 'Green', progress: 55 },
  { id: '17', name: 'Agile Methodology Adoption', theme: 'Business Excellence & Transformation', description: 'Roll out Agile methodologies across the Technology department.', objectives: 'Increase development speed and team responsiveness.', leads: ['8', '2'], teamMembers: ['6', '10'], status: 'In Progress', priority: 'Medium', startDate: '2024-02-20', targetEndDate: '2024-08-20', tags: ['Agile', 'Process'], ragStatus: 'Green', progress: 75 },
  { id: '18', name: 'Logistics Network Optimization', theme: 'MSW & WTE', description: 'Optimize the collection routes for waste management trucks.', objectives: 'Reduce fuel costs and carbon emissions by 10%.', leads: ['9'], teamMembers: ['6'], status: 'In Progress', priority: 'Medium', startDate: '2024-04-10', targetEndDate: '2024-09-30', tags: ['MSW', 'Logistics'], ragStatus: 'Amber', progress: 35 },
  { id: '19', name: 'Compensation & Benefits Review', theme: 'HR', description: 'Conduct a market review of all employee compensation and benefits packages.', objectives: 'Ensure market competitiveness to attract and retain talent.', leads: ['13'], teamMembers: ['7', '11'], status: 'Not Started', priority: 'High', startDate: '2024-09-01', targetEndDate: '2024-12-31', tags: ['HR', 'Compensation'], ragStatus: 'Green', progress: 0 },
  { id: '20', name: 'Investor Relations Portal', theme: 'Finance', description: 'Develop a secure online portal for investors.', objectives: 'Improve communication and transparency with investors.', leads: ['4'], teamMembers: ['11', '10'], status: 'Completed', priority: 'Medium', startDate: '2023-10-15', targetEndDate: '2024-02-29', tags: ['Finance', 'Digital'], ragStatus: 'Green', progress: 100 },
  { id: '21', name: 'Intellectual Property Strategy', theme: 'Legal', description: 'Develop a comprehensive strategy for protecting the company\'s intellectual property.', objectives: 'File new patents and trademarks for key innovations.', leads: ['5'], teamMembers: ['12', '2'], status: 'In Progress', priority: 'Medium', startDate: '2024-05-15', targetEndDate: '2024-11-15', tags: ['Legal', 'IP'], ragStatus: 'Green', progress: 20 },
  { id: '22', name: 'Supply Chain Resilience Program', theme: 'Business Excellence & Transformation', description: 'Diversify suppliers and build a more resilient supply chain.', objectives: 'Mitigate risks of single-source dependencies.', leads: ['8'], teamMembers: ['6'], status: 'In Progress', priority: 'High', startDate: '2024-06-01', targetEndDate: '2025-03-31', tags: ['Supply Chain', 'Risk'], ragStatus: 'Amber', progress: 10 },
  { id: '23', name: 'Community Outreach for WTE Plant', theme: 'MSW & WTE', description: 'Launch a community outreach and education program about the WTE plant.', objectives: 'Improve public perception and support.', leads: ['9'], teamMembers: ['3'], status: 'Not Started', priority: 'Low', startDate: '2024-08-15', targetEndDate: '2025-01-15', tags: ['WTE', 'Community'], ragStatus: 'Green', progress: 0 },
  { id: '24', name: 'Diversity and Inclusion Initiative', theme: 'HR', description: 'Launch new programs to promote diversity and inclusion in the workplace.', objectives: 'Increase diversity in leadership roles by 15%.', leads: ['13'], teamMembers: ['7', '1'], status: 'In Progress', priority: 'High', startDate: '2024-02-01', targetEndDate: '2024-12-31', tags: ['HR', 'D&I'], ragStatus: 'Green', progress: 50 },
  { id: '25', name: 'Treasury Management System Implementation', theme: 'Finance', description: 'Implement a new system for treasury and cash management.', objectives: 'Optimize cash flow and investment returns.', leads: ['4'], teamMembers: ['11'], status: 'In Progress', priority: 'Medium', startDate: '2024-06-10', targetEndDate: '2024-12-20', tags: ['Finance', 'Digital'], ragStatus: 'Green', progress: 5 },
  { id: '26', name: 'Contract Lifecycle Management (CLM) Tool', theme: 'Legal', description: 'Select and implement a CLM tool.', objectives: 'Automate contract creation, approval, and storage.', leads: ['5'], teamMembers: ['12', '10'], status: 'Not Started', priority: 'Medium', startDate: '2024-07-20', targetEndDate: '2025-02-20', tags: ['Legal', 'Automation', 'Digital'], ragStatus: 'Green', progress: 0 },
  { id: '27', name: 'Robotic Process Automation (RPA) Pilot', theme: 'Business Excellence & Transformation', description: 'Pilot RPA for repetitive tasks in Finance and HR.', objectives: 'Prove ROI for wider RPA implementation.', leads: ['8', '2'], teamMembers: ['6', '7', '11'], status: 'In Progress', priority: 'Medium', startDate: '2024-05-25', targetEndDate: '2024-09-25', tags: ['RPA', 'Automation'], ragStatus: 'Green', progress: 40 },
  { id: '28', name: 'Hazardous Waste Disposal Policy', theme: 'MSW & WTE', description: 'Develop and implement a new policy for hazardous waste disposal.', objectives: 'Ensure 100% compliance with environmental regulations.', leads: ['9'], teamMembers: ['5'], status: 'Completed', priority: 'High', startDate: '2023-12-01', targetEndDate: '2024-04-30', tags: ['MSW', 'Compliance', 'Legal'], ragStatus: 'Green', progress: 100 },
  { id: '29', name: 'Employee Wellness Program', theme: 'HR', description: 'Launch a comprehensive wellness program for all employees.', objectives: 'Improve employee well-being and reduce sick days.', leads: ['13'], teamMembers: ['7'], status: 'On Hold', priority: 'Low', startDate: '2024-06-01', targetEndDate: '2024-11-30', tags: ['HR', 'Wellness'], ragStatus: 'Red', progress: 10 },
  { id: '30', name: 'Cost Optimization Analysis', theme: 'Finance', description: 'Conduct a company-wide analysis to identify cost-saving opportunities.', objectives: 'Identify potential savings of at least 5% of operating costs.', leads: ['4'], teamMembers: ['11', '6'], status: 'In Progress', priority: 'High', startDate: '2024-05-01', targetEndDate: '2024-08-31', tags: ['Finance', 'Cost'], ragStatus: 'Green', progress: 30 },
];

const tasks: Task[] = [
  { id: '1', initiativeId: '1', title: 'Gather all vendor agreements', description: 'Collect all contracts from the procurement department.', ownerId: '12', contributorIds: [], status: 'Completed', startDate: '2024-01-15', dueDate: '2024-02-15', progress: 100 },
  { id: '2', initiativeId: '1', title: 'Analyze termination clauses', description: 'Review all termination clauses for risks.', ownerId: '5', contributorIds: ['12'], status: 'In Progress', startDate: '2024-02-16', dueDate: '2024-05-30', progress: 70 },
  { id: '3', initiativeId: '6', title: 'Define digital strategy pillars', description: 'Workshop with leadership to define key pillars.', ownerId: '8', contributorIds: ['2', '1'], status: 'In Progress', startDate: '2024-01-15', dueDate: '2024-03-15', progress: 90 },
  { id: '4', initiativeId: '6', title: 'Select technology platforms', description: 'Evaluate and select key technology vendors.', ownerId: '2', contributorIds: ['10', '8'], status: 'In Progress', startDate: '2024-03-16', dueDate: '2024-06-30', progress: 40 },
  { id: '5', initiativeId: '11', title: 'Configure performance review workflows', description: 'Set up the workflows in the new HR system.', ownerId: '7', contributorIds: ['2'], status: 'Completed', startDate: '2024-02-01', dueDate: '2024-04-30', progress: 100 },
  { id: '6', initiativeId: '11', title: 'Train managers on new system', description: 'Conduct training sessions for all people managers.', ownerId: '13', contributorIds: ['7'], status: 'In Progress', startDate: '2024-05-01', dueDate: '2024-06-15', progress: 20 },
  { id: '7', initiativeId: '14', title: 'Data migration planning', description: 'Plan the migration of financial data to S/4HANA.', ownerId: '11', contributorIds: ['10'], status: 'In Progress', startDate: '2023-07-01', dueDate: '2024-07-30', progress: 80, parentTaskId: undefined },
  { id: '8', initiativeId: '14', title: 'Finalize data cleansing for migration', description: 'Cleanse legacy data before migration.', ownerId: '11', contributorIds: [], status: 'Blocked', startDate: '2024-07-01', dueDate: '2024-07-30', progress: 50, parentTaskId: '7' },
  { id: '9', initiativeId: '1', title: 'Final Report Generation', description: 'Generate final report with all findings.', ownerId: '5', contributorIds: ['12'], status: 'Not Started', startDate: '2024-06-01', dueDate: '2024-06-30', progress: 0 },
  { id: '10', initiativeId: '6', title: 'Develop business cases for each pillar', description: 'Create detailed business cases.', ownerId: '8', contributorIds: ['3', '4'], status: 'Not Started', startDate: '2024-07-01', dueDate: '2024-08-30', progress: 0 },
];

const initiativeRatings: InitiativeRating[] = [
    { id: '1', initiativeId: '4', ratedBy: '1', period: 'Closure', impactScore: 5, timelinessScore: 5, executionScore: 4, collaborationScore: 5, overallScore: 4.75, comments: 'Excellent execution, delivered ahead of schedule.', createdAt: '2024-02-05' },
    { id: '2', initiativeId: '10', ratedBy: '1', period: 'Closure', impactScore: 4, timelinessScore: 5, executionScore: 4, collaborationScore: 4, overallScore: 4.25, comments: 'Good project, achieved its main goals.', createdAt: '2024-04-02' },
];

const userRatings: UserRating[] = [
    { id: '1', initiativeId: '4', userId: '5', ratedBy: '1', ownershipScore: 5, qualityScore: 5, timelinessScore: 5, collaborationScore: 4, overallScore: 4.75, comments: 'Great leadership and vision.', createdAt: '2024-02-05' },
    { id: '2', initiativeId: '4', userId: '12', ratedBy: '5', ownershipScore: 5, qualityScore: 4, timelinessScore: 5, collaborationScore: 5, overallScore: 4.75, comments: 'Very diligent and proactive.', createdAt: '2024-02-04' },
    { id: '3', initiativeId: '4', userId: '3', ratedBy: '5', ownershipScore: 4, qualityScore: 5, timelinessScore: 4, collaborationScore: 5, overallScore: 4.5, comments: 'Excellent contributions from a marketing perspective.', createdAt: '2024-02-04' },
];

const dailyCheckins: DailyCheckin[] = [
    { id: '1', initiativeId: '1', date: '2024-05-20', ragStatus: 'Green', summary: 'Completed review of Q1 contracts. No major issues found.', createdBy: '5' },
    { id: '2', initiativeId: '6', date: '2024-05-20', ragStatus: 'Amber', summary: 'Vendor selection is delayed due to contract negotiations. Potential 1-week slip.', createdBy: '2' },
];

const attachments: Attachment[] = [
    { id: '1', type: 'initiative', parentId: '1', fileName: 'Legal Review Kick-off.pptx', fileType: 'PPT', driveFileId: '123', driveUrl: '#', uploadedBy: '5', uploadedAt: '2024-01-15' },
    { id: '2', type: 'task', parentId: '1', fileName: 'Procurement_Agreements_Export.zip', fileType: 'ZIP', driveFileId: '456', driveUrl: '#', uploadedBy: '12', uploadedAt: '2024-02-10' },
];

export const getUsers = () => users;
export const getUser = (id: string) => users.find(u => u.id === id);

export const getInitiatives = () => initiatives;
export const getInitiative = (id: string) => initiatives.find(i => i.id === id);

export const getTasks = () => tasks;
export const getTask = (id: string) => tasks.find(t => t.id === id);
export const getTasksForInitiative = (initiativeId: string) => tasks.filter(t => t.initiativeId === initiativeId);
export const getTasksForUser = (userId: string) => tasks.filter(t => t.ownerId === userId || t.contributorIds.includes(userId));

export const getInitiativeRatings = (initiativeId: string) => initiativeRatings.filter(r => r.initiativeId === initiativeId);
export const getUserRatings = (initiativeId: string) => userRatings.filter(r => r.initiativeId === initiativeId);
export const getDailyCheckins = (initiativeId: string) => dailyCheckins.filter(c => c.initiativeId === initiativeId);
export const getAttachments = (parentId: string) => attachments.filter(a => a.parentId === parentId);